name: 'Build restreamer dev images'

on:
    workflow_dispatch:
    workflow_call:
    schedule:
        - cron: '37 5 * * *'
    push:
        branches-ignore:
            - '**'

jobs:
    docker:
        runs-on: [self-hosted]
        strategy:
            matrix:
                include:
                    - ui: dev
                      core: core-dev-alpine3.19
                      ffmpeg: ffmpeg6.1.1-alpine3.19
                      platforms: linux/amd64,linux/arm64,linux/arm/v7
                      name: dev
                    - ui: dev
                      core: core-dev-alpine3.19
                      ffmpeg: ffmpeg6.1.1-rpi-alpine3.19
                      platforms: linux/arm64,linux/arm/v7
                      name: rpi-dev
                    - ui: dev
                      core: core-dev-ubuntu20.04
                      ffmpeg: ffmpeg6.1.1-vaapi-ubuntu20.04
                      platforms: linux/amd64
                      name: vaapi-dev
                    - ui: dev
                      core: core-dev-ubuntu20.04
                      ffmpeg: ffmpeg6.1.1-cuda-ubuntu20.04-cuda11.7.1
                      platforms: linux/amd64
                      name: cuda-dev
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      datarhei/restreamer
                  tags: |
                      type=raw,value=${{ matrix.name }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@master
              with:
                  platforms: all

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@master

            - name: Login to DockerHub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Multi-Arch
              uses: docker/build-push-action@v5
              with:
                  builder: ${{ steps.buildx.outputs.name }}
                  context: .
                  file: ./Dockerfile
                  build-args: |
                      RESTREAMER_UI_IMAGE=datarhei/restreamer-ui:${{ matrix.ui }}
                      CORE_IMAGE=datarhei/base:${{ matrix.core }}
                      FFMPEG_IMAGE=datarhei/base:${{ matrix.ffmpeg }}
                  platforms: ${{ matrix.platforms }}
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
